version: '3'

services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_test:/var/lib/postgresql/data_test

  php:
    build:
      context: .
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db
    command: make start

volumes:
  pgdata:
  pgdata_test: